import Head from "next/head";
import Navbar from "@/components/Navbar";
import Body from "@/components/Body";

export default function Home() {
  return (
    <>
      <Head>
        <title>\Pet Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Body/>
    </>
  );
}
