import Head from "next/head";
import Navbar from "@/components/Navbar";
import Body from "@/components/Body";
import { motion } from "framer-motion";

export default function Home() {
  return (
    <>
      <Head>
        <title>\Pet Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8, ease: "easeOut" }}
      ></motion.div>
      
      <Navbar/>
      <Body/>
    </>
  );
}
